use_directory_urls: false
site_author: Zachary Loeber
copyright: PSVVX is licensed under this <a href='https://github.com/zloeber/psvvx/blob/master/License.md'> license
theme: readthedocs
site_name: PSVVX Docs
pages:
- Acknowledgements: Acknowledgements.md
- ChangeLog: ChangeLog.md
- Contributing: Contributing.md
- Index: Index.md
- Functions:
  - Get-VVXCallStatus: Functions/Get-VVXCallStatus.md
  - Get-VVXLastRESTCall: Functions/Get-VVXLastRESTCall.md
  - Send-VVXRestCommand: Functions/Send-VVXRestCommand.md
repo_url: https://github.com/zloeber/psvvx

